// Generated from crawl_similar/reguli_similar.json (world string instruments).
// Each suggestion: short name w/ instrument + Ample equivalent ('similar') + context (EN).
export interface SimilarSuggestion { suggestion:string; instrument:string; type:string; similar:string; context:string }
export const SIMILAR_SUGGESTIONS: SimilarSuggestion[] = [
  {"suggestion": "flamenco_rasgueado", "instrument": "Flamenco guitar", "type": "articulation", "similar": "≈ Rasgueado", "context": "progressions/rhythm"},
  {"suggestion": "flamenco_alzapúa", "instrument": "Flamenco guitar", "type": "articulation", "similar": "≈ Alzapúa", "context": "progressions/rhythm"},
  {"suggestion": "flamenco_picado", "instrument": "Flamenco guitar", "type": "articulation", "similar": "≈ alternate picking", "context": "melody"},
  {"suggestion": "flamenco_golpe", "instrument": "Flamenco guitar", "type": "articulation", "similar": "≈ Golpe/Body Hit", "context": "rhythm"},
  {"suggestion": "flamenco_tremolo", "instrument": "Flamenco guitar", "type": "articulation", "similar": "≈ Tremolo", "context": "melody/arp"},
  {"suggestion": "flamenco_zgomot", "instrument": "Flamenco guitar", "type": "fx", "similar": "≈ Body Hit", "context": "rhythm"},
  {"suggestion": "oud_pizzicato", "instrument": "Oud", "type": "articulation", "similar": "≈ Sustain", "context": "melody"},
  {"suggestion": "oud_tremolo", "instrument": "Oud", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "oud_glissando", "instrument": "Oud", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "oud_ornament", "instrument": "Oud", "type": "articulation", "similar": "≈ Hammer-on/Pull-off", "context": "melody"},
  {"suggestion": "oud_rezonanță", "instrument": "Oud", "type": "fx", "similar": "≈ Body Hit", "context": "accent"},
  {"suggestion": "sitar_meend", "instrument": "Sitar", "type": "articulation", "similar": "≈ Bend / Legato Slide", "context": "melody"},
  {"suggestion": "sitar_gamak", "instrument": "Sitar", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "sitar_krintan", "instrument": "Sitar", "type": "articulation", "similar": "≈ Pull-off", "context": "melody"},
  {"suggestion": "sitar_zamzama", "instrument": "Sitar", "type": "articulation", "similar": "≈ tremolo", "context": "melody"},
  {"suggestion": "sitar_javari", "instrument": "Sitar", "type": "fx", "similar": "≈ String Buzz", "context": "sustain/drone"},
  {"suggestion": "sitar_chikari", "instrument": "Sitar", "type": "fx", "similar": "≈ Strum accent", "context": "ostinato"},
  {"suggestion": "banjo_rolls", "instrument": "Banjo", "type": "articulation", "similar": "≈ arpeggio/Travis", "context": "ostinato/progresii"},
  {"suggestion": "banjo_hammer-on", "instrument": "Banjo", "type": "articulation", "similar": "≈ Hammer-on", "context": "melody"},
  {"suggestion": "banjo_pull-off", "instrument": "Banjo", "type": "articulation", "similar": "≈ Pull-off", "context": "melody"},
  {"suggestion": "banjo_slide", "instrument": "Banjo", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "banjo_rezonanță", "instrument": "Banjo", "type": "fx", "similar": "≈ Staccato", "context": "rhythm"},
  {"suggestion": "mandolin_tremolo", "instrument": "Mandolin", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "mandolin_pizzicato", "instrument": "Mandolin", "type": "articulation", "similar": "≈ Sustain", "context": "melody"},
  {"suggestion": "mandolin_slide", "instrument": "Mandolin", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "mandolin_attack", "instrument": "Mandolin", "type": "fx", "similar": "≈ Strum", "context": "progressions"},
  {"suggestion": "bouzouki_tremolo", "instrument": "Bouzouki", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "bouzouki_slide", "instrument": "Bouzouki", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "bouzouki_hammer-on", "instrument": "Bouzouki", "type": "articulation", "similar": "≈ Hammer-on", "context": "melody"},
  {"suggestion": "bouzouki_zgomot", "instrument": "Bouzouki", "type": "fx", "similar": "≈ Pick Scratch", "context": "rhythm"},
  {"suggestion": "charango_rasgueo", "instrument": "Charango", "type": "articulation", "similar": "≈ Rasgueado", "context": "rhythm"},
  {"suggestion": "charango_tremolo", "instrument": "Charango", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "charango_slide", "instrument": "Charango", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "charango_brightness", "instrument": "Charango", "type": "fx", "similar": "≈ Strum", "context": "progressions"},
  {"suggestion": "cavaquinho_rasgado", "instrument": "Cavaquinho", "type": "articulation", "similar": "≈ Rasgueado", "context": "rhythm"},
  {"suggestion": "cavaquinho_pizzicato", "instrument": "Cavaquinho", "type": "articulation", "similar": "≈ Sustain", "context": "melody"},
  {"suggestion": "cavaquinho_percuție", "instrument": "Cavaquinho", "type": "fx", "similar": "≈ Body Hit", "context": "rhythm"},
  {"suggestion": "tres_arpegio", "instrument": "Cuban tres", "type": "articulation", "similar": "≈ arpeggio", "context": "ostinato"},
  {"suggestion": "tres_slide", "instrument": "Cuban tres", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "tres_zgomot", "instrument": "Cuban tres", "type": "fx", "similar": "≈ Strum", "context": "ostinato"},
  {"suggestion": "kora_ornamente", "instrument": "Kora", "type": "articulation", "similar": "≈ Hammer-on/Pull-off", "context": "melody"},
  {"suggestion": "kora_arpegii", "instrument": "Kora", "type": "articulation", "similar": "≈ arpeggio", "context": "ostinato"},
  {"suggestion": "kora_rezonanță", "instrument": "Kora", "type": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"suggestion": "balalaika_tremolo", "instrument": "Balalaika", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "balalaika_pizzicato", "instrument": "Balalaika", "type": "articulation", "similar": "≈ Sustain", "context": "melody"},
  {"suggestion": "balalaika_vibrato", "instrument": "Balalaika", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "balalaika_bătaie", "instrument": "Balalaika", "type": "fx", "similar": "≈ Body Hit", "context": "rhythm"},
  {"suggestion": "saz_tremolo", "instrument": "Saz/Baglama", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "saz_slide", "instrument": "Saz/Baglama", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "saz_mordent", "instrument": "Saz/Baglama", "type": "articulation", "similar": "≈ Hammer-on/Pull-off", "context": "melody"},
  {"suggestion": "saz_zgomot", "instrument": "Saz/Baglama", "type": "fx", "similar": "≈ Pick Scratch", "context": "rhythm"},
  {"suggestion": "erhu_vibrato", "instrument": "Erhu", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "erhu_slide", "instrument": "Erhu", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "erhu_glissando", "instrument": "Erhu", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "erhu_rezonanță", "instrument": "Erhu", "type": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"suggestion": "pipa_lun", "instrument": "Pipa", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "pipa_yin", "instrument": "Pipa", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "pipa_sao", "instrument": "Pipa", "type": "articulation", "similar": "≈ Strum/Rasgueado", "context": "progressions"},
  {"suggestion": "pipa_lun指", "instrument": "Pipa", "type": "articulation", "similar": "≈ arpeggio", "context": "arp"},
  {"suggestion": "pipa_zgomot", "instrument": "Pipa", "type": "fx", "similar": "≈ String Scratch", "context": "rhythm"},
  {"suggestion": "koto_vibrato", "instrument": "Koto", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "koto_glissando", "instrument": "Koto", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "koto_tremolo", "instrument": "Koto", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "koto_slide", "instrument": "Koto", "type": "fx", "similar": "≈ Slide FX", "context": "ambient"},
  {"suggestion": "guzheng_vibrato", "instrument": "Guzheng", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "guzheng_slide", "instrument": "Guzheng", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "guzheng_tremolo", "instrument": "Guzheng", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "guzheng_glissando", "instrument": "Guzheng", "type": "fx", "similar": "≈ Slide FX", "context": "ambient"},
  {"suggestion": "portugueza_trinado", "instrument": "Portuguese guitar", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "portugueza_glissando", "instrument": "Portuguese guitar", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "portugueza_arpejo", "instrument": "Portuguese guitar", "type": "articulation", "similar": "≈ arpeggio", "context": "arp"},
  {"suggestion": "portugueza_rezonanță", "instrument": "Portuguese guitar", "type": "fx", "similar": "≈ Strum", "context": "progressions"},
  {"suggestion": "steel_slide", "instrument": "Steel guitar (dobro)", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "steel_vibrato", "instrument": "Steel guitar (dobro)", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "steel_hammer-on", "instrument": "Steel guitar (dobro)", "type": "articulation", "similar": "≈ Hammer-on", "context": "melody"},
  {"suggestion": "steel_bar", "instrument": "Steel guitar (dobro)", "type": "fx", "similar": "≈ Slide FX", "context": "melody"},
  {"suggestion": "12corzi_strum", "instrument": "12-string guitar", "type": "articulation", "similar": "≈ Strum", "context": "progressions"},
  {"suggestion": "12corzi_arpeggio", "instrument": "12-string guitar", "type": "articulation", "similar": "≈ arpeggio", "context": "arp"},
  {"suggestion": "12corzi_chorus", "instrument": "12-string guitar", "type": "fx", "similar": "≈ (cor dublat)", "context": "progressions"},
  {"suggestion": "bass_slap", "instrument": "Bass (electric)", "type": "articulation", "similar": "≈ Slap", "context": "bass"},
  {"suggestion": "bass_pop", "instrument": "Bass (electric)", "type": "articulation", "similar": "≈ Pop", "context": "bass"},
  {"suggestion": "bass_hammer-on", "instrument": "Bass (electric)", "type": "articulation", "similar": "≈ Hammer-on", "context": "bass"},
  {"suggestion": "bass_slide", "instrument": "Bass (electric)", "type": "articulation", "similar": "≈ Slide", "context": "bass"},
  {"suggestion": "bass_thumb", "instrument": "Bass (electric)", "type": "fx", "similar": "≈ Slap noise", "context": "bass"},
  {"suggestion": "bass_pop", "instrument": "Bass (electric)", "type": "fx", "similar": "≈ Pop noise", "context": "bass"},
  {"suggestion": "tar_vibrato", "instrument": "Tar", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "tar_glissando", "instrument": "Tar", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "tar_tremolo", "instrument": "Tar", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "tar_rezonanță", "instrument": "Tar", "type": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"suggestion": "setar_vibrato", "instrument": "Setar", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "setar_slide", "instrument": "Setar", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "setar_tremolo", "instrument": "Setar", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "setar_zgomot", "instrument": "Setar", "type": "fx", "similar": "≈ Fret Noise", "context": "melody"},
  {"suggestion": "shamisen_sukui", "instrument": "Shamisen", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "shamisen_vibrato", "instrument": "Shamisen", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "shamisen_hajiki", "instrument": "Shamisen", "type": "articulation", "similar": "≈ Pull-off", "context": "melody"},
  {"suggestion": "shamisen_uchi", "instrument": "Shamisen", "type": "articulation", "similar": "≈ Dead Note/strum", "context": "rhythm"},
  {"suggestion": "shamisen_bachi", "instrument": "Shamisen", "type": "fx", "similar": "≈ Pick Scratch", "context": "rhythm"},
  {"suggestion": "biwa_tremolo", "instrument": "Biwa", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "biwa_slide", "instrument": "Biwa", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "biwa_strum", "instrument": "Biwa", "type": "articulation", "similar": "≈ Strum/Dead Note", "context": "rhythm"},
  {"suggestion": "biwa_lovitură", "instrument": "Biwa", "type": "fx", "similar": "≈ Body Hit", "context": "rhythm"},
  {"suggestion": "rubab_tremolo", "instrument": "Rubab", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "rubab_slide", "instrument": "Rubab", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "rubab_hammer-on", "instrument": "Rubab", "type": "articulation", "similar": "≈ Hammer-on", "context": "melody"},
  {"suggestion": "rubab_rezonanță", "instrument": "Rubab", "type": "fx", "similar": "≈ (corzi simpatice)", "context": "ambient"},
  {"suggestion": "qanun_tremolo", "instrument": "Qanun", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "qanun_glissando", "instrument": "Qanun", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "qanun_mandals", "instrument": "Qanun", "type": "articulation", "similar": "≈ Bend", "context": "melody"},
  {"suggestion": "qanun_click", "instrument": "Qanun", "type": "fx", "similar": "≈ (switch)", "context": "melody"},
  {"suggestion": "santur_tremolo", "instrument": "Santur", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "santur_glissando", "instrument": "Santur", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "santur_rezonanță", "instrument": "Santur", "type": "fx", "similar": "≈ chorus", "context": "ambient"},
  {"suggestion": "gayageum_nonghyeon", "instrument": "Gayageum", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "gayageum_chwihyeon", "instrument": "Gayageum", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "gayageum_tremolo", "instrument": "Gayageum", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "gayageum_rezonanță", "instrument": "Gayageum", "type": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"suggestion": "veena_gamaka", "instrument": "Veena", "type": "articulation", "similar": "≈ Vibrato/Bend", "context": "melody"},
  {"suggestion": "veena_slide", "instrument": "Veena", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "veena_pull-off", "instrument": "Veena", "type": "articulation", "similar": "≈ Pull-off", "context": "melody"},
  {"suggestion": "veena_rezonanță", "instrument": "Veena", "type": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"suggestion": "sarangi_vibrato", "instrument": "Sarangi", "type": "articulation", "similar": "≈ Vibrato/Slide", "context": "melody"},
  {"suggestion": "sarangi_glissando", "instrument": "Sarangi", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "sarangi_rezonanță", "instrument": "Sarangi", "type": "fx", "similar": "≈ (corzi simpatice)", "context": "ambient"},
  {"suggestion": "cumbus_tremolo", "instrument": "Cümbüş", "type": "articulation", "similar": "≈ Tremolo", "context": "melody"},
  {"suggestion": "cumbus_slide", "instrument": "Cümbüş", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "cumbus_rezonanță", "instrument": "Cümbüş", "type": "fx", "similar": "≈ banjo", "context": "progressions"},
  {"suggestion": "lute_pizzicato", "instrument": "Lute/Renaissance", "type": "articulation", "similar": "≈ Sustain", "context": "melody"},
  {"suggestion": "lute_ornamente", "instrument": "Lute/Renaissance", "type": "articulation", "similar": "≈ Hammer-on/Pull-off", "context": "melody"},
  {"suggestion": "lute_arpeggio", "instrument": "Lute/Renaissance", "type": "articulation", "similar": "≈ arpeggio", "context": "arp"},
  {"suggestion": "lute_rezonanție", "instrument": "Lute/Renaissance", "type": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"suggestion": "vihuela_rasgueado", "instrument": "Vihuela", "type": "articulation", "similar": "≈ Rasgueado", "context": "rhythm"},
  {"suggestion": "vihuela_arpegio", "instrument": "Vihuela", "type": "articulation", "similar": "≈ arpeggio", "context": "arp"},
  {"suggestion": "vihuela_slide", "instrument": "Vihuela", "type": "articulation", "similar": "≈ Slide", "context": "melody"},
  {"suggestion": "vihuela_percuție", "instrument": "Vihuela", "type": "fx", "similar": "≈ Body Hit", "context": "rhythm"},
  {"suggestion": "timple_rasgueado", "instrument": "Timple", "type": "articulation", "similar": "≈ Rasgueado", "context": "rhythm"},
  {"suggestion": "timple_tremolo", "instrument": "Timple", "type": "articulation", "similar": "≈ Vibrato", "context": "melody"},
  {"suggestion": "timple_brightness", "instrument": "Timple", "type": "fx", "similar": "≈ Strum", "context": "progressions"},
  {"suggestion": "harpa_glissando", "instrument": "Harp", "type": "articulation", "similar": "≈ Slide FX", "context": "arp/melody"},
  {"suggestion": "harpa_pizzicato", "instrument": "Harp", "type": "articulation", "similar": "≈ Sustain", "context": "melody"},
  {"suggestion": "harpa_arpegii", "instrument": "Harp", "type": "articulation", "similar": "≈ arpeggio", "context": "arp"},
  {"suggestion": "harpa_rezonanție", "instrument": "Harp", "type": "fx", "similar": "≈ chorus", "context": "ambient"},
  {"suggestion": "mandola_tremolo", "instrument": "Mandola / octave mandolin", "type": "articulation", "similar": "≈ Vibrato/Tremolo", "context": "melody"},
  {"suggestion": "mandola_strum", "instrument": "Mandola / octave mandolin", "type": "articulation", "similar": "≈ Strum", "context": "progressions"},
  {"suggestion": "mandola_attack", "instrument": "Mandola / octave mandolin", "type": "fx", "similar": "≈ Strum", "context": "progressions"},
];
