// Generat din crawl_similar/reguli_similar.json (instrumente cu corzi din lume).
// Fiecare sugestie: denumire scurta cu instrumentul + echivalent Ample ('≈') + context.
export interface SugestieSimilara { sugestie:string; instrument:string; tip:string; similar:string; context:string }
export const SUGESTII_SIMILARE: SugestieSimilara[] = [
  {"sugestie": "flamenco_rasgueado", "instrument": "Chitara flamenco", "tip": "articulatie", "similar": "≈ Rasgueado", "context": "progresii/ritm"},
  {"sugestie": "flamenco_alzapúa", "instrument": "Chitara flamenco", "tip": "articulatie", "similar": "≈ Alzapúa", "context": "progresii/ritm"},
  {"sugestie": "flamenco_picado", "instrument": "Chitara flamenco", "tip": "articulatie", "similar": "≈ alternate picking", "context": "melodie"},
  {"sugestie": "flamenco_golpe", "instrument": "Chitara flamenco", "tip": "articulatie", "similar": "≈ Golpe/Body Hit", "context": "ritm"},
  {"sugestie": "flamenco_tremolo", "instrument": "Chitara flamenco", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie/arp"},
  {"sugestie": "flamenco_zgomot", "instrument": "Chitara flamenco", "tip": "fx", "similar": "≈ Body Hit", "context": "ritm"},
  {"sugestie": "oud_pizzicato", "instrument": "Oud", "tip": "articulatie", "similar": "≈ Sustain", "context": "melodie"},
  {"sugestie": "oud_tremolo", "instrument": "Oud", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "oud_glissando", "instrument": "Oud", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "oud_ornament", "instrument": "Oud", "tip": "articulatie", "similar": "≈ Hammer-on/Pull-off", "context": "melodie"},
  {"sugestie": "oud_rezonanță", "instrument": "Oud", "tip": "fx", "similar": "≈ Body Hit", "context": "accent"},
  {"sugestie": "sitar_meend", "instrument": "Sitar", "tip": "articulatie", "similar": "≈ Bend / Legato Slide", "context": "melodie"},
  {"sugestie": "sitar_gamak", "instrument": "Sitar", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "sitar_krintan", "instrument": "Sitar", "tip": "articulatie", "similar": "≈ Pull-off", "context": "melodie"},
  {"sugestie": "sitar_zamzama", "instrument": "Sitar", "tip": "articulatie", "similar": "≈ tremolo", "context": "melodie"},
  {"sugestie": "sitar_javari", "instrument": "Sitar", "tip": "fx", "similar": "≈ String Buzz", "context": "sustain/drone"},
  {"sugestie": "sitar_chikari", "instrument": "Sitar", "tip": "fx", "similar": "≈ Strum accent", "context": "ostinato"},
  {"sugestie": "banjo_rolls", "instrument": "Banjo", "tip": "articulatie", "similar": "≈ arpeggio/Travis", "context": "ostinato/progresii"},
  {"sugestie": "banjo_hammer-on", "instrument": "Banjo", "tip": "articulatie", "similar": "≈ Hammer-on", "context": "melodie"},
  {"sugestie": "banjo_pull-off", "instrument": "Banjo", "tip": "articulatie", "similar": "≈ Pull-off", "context": "melodie"},
  {"sugestie": "banjo_slide", "instrument": "Banjo", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "banjo_rezonanță", "instrument": "Banjo", "tip": "fx", "similar": "≈ Staccato", "context": "ritm"},
  {"sugestie": "mandolin_tremolo", "instrument": "Mandolin", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "mandolin_pizzicato", "instrument": "Mandolin", "tip": "articulatie", "similar": "≈ Sustain", "context": "melodie"},
  {"sugestie": "mandolin_slide", "instrument": "Mandolin", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "mandolin_attack", "instrument": "Mandolin", "tip": "fx", "similar": "≈ Strum", "context": "progresii"},
  {"sugestie": "bouzouki_tremolo", "instrument": "Bouzouki", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "bouzouki_slide", "instrument": "Bouzouki", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "bouzouki_hammer-on", "instrument": "Bouzouki", "tip": "articulatie", "similar": "≈ Hammer-on", "context": "melodie"},
  {"sugestie": "bouzouki_zgomot", "instrument": "Bouzouki", "tip": "fx", "similar": "≈ Pick Scratch", "context": "ritm"},
  {"sugestie": "charango_rasgueo", "instrument": "Charango", "tip": "articulatie", "similar": "≈ Rasgueado", "context": "ritm"},
  {"sugestie": "charango_tremolo", "instrument": "Charango", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "charango_slide", "instrument": "Charango", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "charango_brightness", "instrument": "Charango", "tip": "fx", "similar": "≈ Strum", "context": "progresii"},
  {"sugestie": "cavaquinho_rasgado", "instrument": "Cavaquinho", "tip": "articulatie", "similar": "≈ Rasgueado", "context": "ritm"},
  {"sugestie": "cavaquinho_pizzicato", "instrument": "Cavaquinho", "tip": "articulatie", "similar": "≈ Sustain", "context": "melodie"},
  {"sugestie": "cavaquinho_percuție", "instrument": "Cavaquinho", "tip": "fx", "similar": "≈ Body Hit", "context": "ritm"},
  {"sugestie": "tres_arpegio", "instrument": "Tres cubano", "tip": "articulatie", "similar": "≈ arpeggio", "context": "ostinato"},
  {"sugestie": "tres_slide", "instrument": "Tres cubano", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "tres_zgomot", "instrument": "Tres cubano", "tip": "fx", "similar": "≈ Strum", "context": "ostinato"},
  {"sugestie": "kora_ornamente", "instrument": "Kora", "tip": "articulatie", "similar": "≈ Hammer-on/Pull-off", "context": "melodie"},
  {"sugestie": "kora_arpegii", "instrument": "Kora", "tip": "articulatie", "similar": "≈ arpeggio", "context": "ostinato"},
  {"sugestie": "kora_rezonanță", "instrument": "Kora", "tip": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"sugestie": "balalaika_tremolo", "instrument": "Balalaika", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "balalaika_pizzicato", "instrument": "Balalaika", "tip": "articulatie", "similar": "≈ Sustain", "context": "melodie"},
  {"sugestie": "balalaika_vibrato", "instrument": "Balalaika", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "balalaika_bătaie", "instrument": "Balalaika", "tip": "fx", "similar": "≈ Body Hit", "context": "ritm"},
  {"sugestie": "saz_tremolo", "instrument": "Saz/Baglama", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "saz_slide", "instrument": "Saz/Baglama", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "saz_mordent", "instrument": "Saz/Baglama", "tip": "articulatie", "similar": "≈ Hammer-on/Pull-off", "context": "melodie"},
  {"sugestie": "saz_zgomot", "instrument": "Saz/Baglama", "tip": "fx", "similar": "≈ Pick Scratch", "context": "ritm"},
  {"sugestie": "erhu_vibrato", "instrument": "Erhu", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "erhu_slide", "instrument": "Erhu", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "erhu_glissando", "instrument": "Erhu", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "erhu_rezonanță", "instrument": "Erhu", "tip": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"sugestie": "pipa_lun", "instrument": "Pipa", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "pipa_yin", "instrument": "Pipa", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "pipa_sao", "instrument": "Pipa", "tip": "articulatie", "similar": "≈ Strum/Rasgueado", "context": "progresii"},
  {"sugestie": "pipa_lun指", "instrument": "Pipa", "tip": "articulatie", "similar": "≈ arpeggio", "context": "arp"},
  {"sugestie": "pipa_zgomot", "instrument": "Pipa", "tip": "fx", "similar": "≈ String Scratch", "context": "ritm"},
  {"sugestie": "koto_vibrato", "instrument": "Koto", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "koto_glissando", "instrument": "Koto", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "koto_tremolo", "instrument": "Koto", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "koto_slide", "instrument": "Koto", "tip": "fx", "similar": "≈ Slide FX", "context": "ambient"},
  {"sugestie": "guzheng_vibrato", "instrument": "Guzheng", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "guzheng_slide", "instrument": "Guzheng", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "guzheng_tremolo", "instrument": "Guzheng", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "guzheng_glissando", "instrument": "Guzheng", "tip": "fx", "similar": "≈ Slide FX", "context": "ambient"},
  {"sugestie": "portugueza_trinado", "instrument": "Guitarra portuguesa", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "portugueza_glissando", "instrument": "Guitarra portuguesa", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "portugueza_arpejo", "instrument": "Guitarra portuguesa", "tip": "articulatie", "similar": "≈ arpeggio", "context": "arp"},
  {"sugestie": "portugueza_rezonanță", "instrument": "Guitarra portuguesa", "tip": "fx", "similar": "≈ Strum", "context": "progresii"},
  {"sugestie": "steel_slide", "instrument": "Steel guitar (dobro)", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "steel_vibrato", "instrument": "Steel guitar (dobro)", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "steel_hammer-on", "instrument": "Steel guitar (dobro)", "tip": "articulatie", "similar": "≈ Hammer-on", "context": "melodie"},
  {"sugestie": "steel_bar", "instrument": "Steel guitar (dobro)", "tip": "fx", "similar": "≈ Slide FX", "context": "melodie"},
  {"sugestie": "12corzi_strum", "instrument": "Chitara 12 corzi", "tip": "articulatie", "similar": "≈ Strum", "context": "progresii"},
  {"sugestie": "12corzi_arpeggio", "instrument": "Chitara 12 corzi", "tip": "articulatie", "similar": "≈ arpeggio", "context": "arp"},
  {"sugestie": "12corzi_chorus", "instrument": "Chitara 12 corzi", "tip": "fx", "similar": "≈ (cor dublat)", "context": "progresii"},
  {"sugestie": "bass_slap", "instrument": "Bass (electric)", "tip": "articulatie", "similar": "≈ Slap", "context": "bass"},
  {"sugestie": "bass_pop", "instrument": "Bass (electric)", "tip": "articulatie", "similar": "≈ Pop", "context": "bass"},
  {"sugestie": "bass_hammer-on", "instrument": "Bass (electric)", "tip": "articulatie", "similar": "≈ Hammer-on", "context": "bass"},
  {"sugestie": "bass_slide", "instrument": "Bass (electric)", "tip": "articulatie", "similar": "≈ Slide", "context": "bass"},
  {"sugestie": "bass_thumb", "instrument": "Bass (electric)", "tip": "fx", "similar": "≈ Slap noise", "context": "bass"},
  {"sugestie": "bass_pop", "instrument": "Bass (electric)", "tip": "fx", "similar": "≈ Pop noise", "context": "bass"},
  {"sugestie": "tar_vibrato", "instrument": "Tar", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "tar_glissando", "instrument": "Tar", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "tar_tremolo", "instrument": "Tar", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "tar_rezonanță", "instrument": "Tar", "tip": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"sugestie": "setar_vibrato", "instrument": "Setar", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "setar_slide", "instrument": "Setar", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "setar_tremolo", "instrument": "Setar", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "setar_zgomot", "instrument": "Setar", "tip": "fx", "similar": "≈ Fret Noise", "context": "melodie"},
  {"sugestie": "shamisen_sukui", "instrument": "Shamisen", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "shamisen_vibrato", "instrument": "Shamisen", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "shamisen_hajiki", "instrument": "Shamisen", "tip": "articulatie", "similar": "≈ Pull-off", "context": "melodie"},
  {"sugestie": "shamisen_uchi", "instrument": "Shamisen", "tip": "articulatie", "similar": "≈ Dead Note/strum", "context": "ritm"},
  {"sugestie": "shamisen_bachi", "instrument": "Shamisen", "tip": "fx", "similar": "≈ Pick Scratch", "context": "ritm"},
  {"sugestie": "biwa_tremolo", "instrument": "Biwa", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "biwa_slide", "instrument": "Biwa", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "biwa_strum", "instrument": "Biwa", "tip": "articulatie", "similar": "≈ Strum/Dead Note", "context": "ritm"},
  {"sugestie": "biwa_lovitură", "instrument": "Biwa", "tip": "fx", "similar": "≈ Body Hit", "context": "ritm"},
  {"sugestie": "rubab_tremolo", "instrument": "Rubab", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "rubab_slide", "instrument": "Rubab", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "rubab_hammer-on", "instrument": "Rubab", "tip": "articulatie", "similar": "≈ Hammer-on", "context": "melodie"},
  {"sugestie": "rubab_rezonanță", "instrument": "Rubab", "tip": "fx", "similar": "≈ (corzi simpatice)", "context": "ambient"},
  {"sugestie": "qanun_tremolo", "instrument": "Qanun", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "qanun_glissando", "instrument": "Qanun", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "qanun_mandals", "instrument": "Qanun", "tip": "articulatie", "similar": "≈ Bend", "context": "melodie"},
  {"sugestie": "qanun_click", "instrument": "Qanun", "tip": "fx", "similar": "≈ (switch)", "context": "melodie"},
  {"sugestie": "santur_tremolo", "instrument": "Santur", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "santur_glissando", "instrument": "Santur", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "santur_rezonanță", "instrument": "Santur", "tip": "fx", "similar": "≈ chorus", "context": "ambient"},
  {"sugestie": "gayageum_nonghyeon", "instrument": "Gayageum", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "gayageum_chwihyeon", "instrument": "Gayageum", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "gayageum_tremolo", "instrument": "Gayageum", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "gayageum_rezonanță", "instrument": "Gayageum", "tip": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"sugestie": "veena_gamaka", "instrument": "Veena", "tip": "articulatie", "similar": "≈ Vibrato/Bend", "context": "melodie"},
  {"sugestie": "veena_slide", "instrument": "Veena", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "veena_pull-off", "instrument": "Veena", "tip": "articulatie", "similar": "≈ Pull-off", "context": "melodie"},
  {"sugestie": "veena_rezonanță", "instrument": "Veena", "tip": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"sugestie": "sarangi_vibrato", "instrument": "Sarangi", "tip": "articulatie", "similar": "≈ Vibrato/Slide", "context": "melodie"},
  {"sugestie": "sarangi_glissando", "instrument": "Sarangi", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "sarangi_rezonanță", "instrument": "Sarangi", "tip": "fx", "similar": "≈ (corzi simpatice)", "context": "ambient"},
  {"sugestie": "cumbus_tremolo", "instrument": "Cümbüş", "tip": "articulatie", "similar": "≈ Tremolo", "context": "melodie"},
  {"sugestie": "cumbus_slide", "instrument": "Cümbüş", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "cumbus_rezonanță", "instrument": "Cümbüş", "tip": "fx", "similar": "≈ banjo", "context": "progresii"},
  {"sugestie": "lute_pizzicato", "instrument": "Lute/Renaissance", "tip": "articulatie", "similar": "≈ Sustain", "context": "melodie"},
  {"sugestie": "lute_ornamente", "instrument": "Lute/Renaissance", "tip": "articulatie", "similar": "≈ Hammer-on/Pull-off", "context": "melodie"},
  {"sugestie": "lute_arpeggio", "instrument": "Lute/Renaissance", "tip": "articulatie", "similar": "≈ arpeggio", "context": "arp"},
  {"sugestie": "lute_rezonanție", "instrument": "Lute/Renaissance", "tip": "fx", "similar": "≈ Body Hit", "context": "ambient"},
  {"sugestie": "vihuela_rasgueado", "instrument": "Vihuela", "tip": "articulatie", "similar": "≈ Rasgueado", "context": "ritm"},
  {"sugestie": "vihuela_arpegio", "instrument": "Vihuela", "tip": "articulatie", "similar": "≈ arpeggio", "context": "arp"},
  {"sugestie": "vihuela_slide", "instrument": "Vihuela", "tip": "articulatie", "similar": "≈ Slide", "context": "melodie"},
  {"sugestie": "vihuela_percuție", "instrument": "Vihuela", "tip": "fx", "similar": "≈ Body Hit", "context": "ritm"},
  {"sugestie": "timple_rasgueado", "instrument": "Timple", "tip": "articulatie", "similar": "≈ Rasgueado", "context": "ritm"},
  {"sugestie": "timple_tremolo", "instrument": "Timple", "tip": "articulatie", "similar": "≈ Vibrato", "context": "melodie"},
  {"sugestie": "timple_brightness", "instrument": "Timple", "tip": "fx", "similar": "≈ Strum", "context": "progresii"},
  {"sugestie": "harpa_glissando", "instrument": "Harpă", "tip": "articulatie", "similar": "≈ Slide FX", "context": "arp/melodie"},
  {"sugestie": "harpa_pizzicato", "instrument": "Harpă", "tip": "articulatie", "similar": "≈ Sustain", "context": "melodie"},
  {"sugestie": "harpa_arpegii", "instrument": "Harpă", "tip": "articulatie", "similar": "≈ arpeggio", "context": "arp"},
  {"sugestie": "harpa_rezonanție", "instrument": "Harpă", "tip": "fx", "similar": "≈ chorus", "context": "ambient"},
  {"sugestie": "mandola_tremolo", "instrument": "Mandola / octave mandolin", "tip": "articulatie", "similar": "≈ Vibrato/Tremolo", "context": "melodie"},
  {"sugestie": "mandola_strum", "instrument": "Mandola / octave mandolin", "tip": "articulatie", "similar": "≈ Strum", "context": "progresii"},
  {"sugestie": "mandola_attack", "instrument": "Mandola / octave mandolin", "tip": "fx", "similar": "≈ Strum", "context": "progresii"},
];
